name: vqa-outliers
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.13.0
  - aiohttp=3.7.4.post0
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - cudatoolkit=11.0.221
  - dataclasses=0.8
  - dbus=1.13.18
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=2021.6.1
  - future=0.18.2
  - glib=2.68.2
  - google-auth=1.32.1
  - google-auth-oauthlib=0.4.1
  - grpcio=1.38.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.17.0
  - jinja2=3.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - multidict=5.1.0
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - notebook=6.4.0
  - numpy=1.20.2
  - numpy-base=1.20.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.3
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - protobuf=3.17.2
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydeprecate=0.3.0
  - pygments=2.9.0
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.7.1
  - pytorch-lightning=1.3.8
  - pyu2f=0.1.5
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.10
  - torchaudio=0.7.2
  - torchmetrics=0.4.1
  - torchvision=0.8.2
  - tornado=6.1
  - tqdm=4.61.2
  - traitlets=5.0.5
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - annoy==1.17.0
    - blis==0.7.4
    - catalogue==2.0.4
    - click==7.1.2
    - cycler==0.10.0
    - cymem==2.0.5
    - filelock==3.0.12
    - h5py==3.3.0
    - huggingface-hub==0.0.12
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.4.2
    - murmurhash==1.0.5
    - mypy-extensions==0.4.3
    - pathy==0.6.0
    - preshed==3.0.5
    - pydantic==1.7.4
    - regex==2021.7.6
    - sacremoses==0.0.45
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - seaborn==0.11.1
    - smart-open==5.1.0
    - spacy==3.0.6
    - spacy-legacy==3.0.7
    - srsly==2.4.1
    - thinc==8.0.7
    - threadpoolctl==2.1.0
    - tokenizers==0.10.3
    - transformers==4.8.2
    - typed-argument-parser==1.7.0
    - typer==0.3.2
    - typing-inspect==0.7.1
    - wasabi==0.8.2
